//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalwaiBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public int ID { get; set; }
        public Nullable<int> postID { get; set; }
        public string comment1 { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<bool> enabled { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual post post { get; set; }
        public virtual user user { get; set; }
    }
}
