//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalwaiBlog.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class globalwaiBlogEntities : DbContext
    {
        public globalwaiBlogEntities()
            : base("name=globalwaiBlogEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<author> author { get; set; }
        public virtual DbSet<category> category { get; set; }
        public virtual DbSet<comment> comment { get; set; }
        public virtual DbSet<post> post { get; set; }
        public virtual DbSet<tag> tag { get; set; }
        public virtual DbSet<user> user { get; set; }
    
        public virtual ObjectResult<postPorId_Obtener_Result> postPorId_Obtener(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<postPorId_Obtener_Result>("postPorId_Obtener", iDParameter);
        }
    
        public virtual ObjectResult<postsAuthor_Obtener_Result> postsAuthor_Obtener()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<postsAuthor_Obtener_Result>("postsAuthor_Obtener");
        }
    
        public virtual ObjectResult<postLista_Obtener_Result> postLista_Obtener(Nullable<int> pageIndex, Nullable<int> pageSize, ObjectParameter pageCount)
        {
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<postLista_Obtener_Result>("postLista_Obtener", pageIndexParameter, pageSizeParameter, pageCount);
        }
    }
}
